---
title: "Assignment"
author: "Jasmine Reighard"
date: "2023-08-21"
output: github_document
---

```{r}
library(raster)
library(habtools)
library(ggplot2)
library(dplyr)
library(fishualize)

plot(horseshoe)
```
## About me

### Current lab
Johansen Fish Resillience Lab

### Project focus
The effects of sedimentation on herbivorous reef fish

### Why you chose this course
I wanted to broaden my technical skills and stay relevant with my coding knowledge

### What do you want to learn about the most in this course
I am pretty unfamiliar with what technologies we will be learning, so I'm just excited to become familiar with new software and maybe apply it to my graduate research!

### Your R experience
Intermediate. I've taken two courses in R for statistics so my codebank is pretty basic but useful. 

### Fun fact
I fell in love with Pacific spiny lumpsuckers this summer at Friday Harbor Laboratories. I really want to have an emotional support tank of them at home or HIMB. (Side note: They can only survive in cold water environments so there isn't really a chance for them to become an invasive species if for some reason they got loose.)
